
###
POST  http://localhost:3000/post HTTP/1.1
Content-Type: application/json

{
    "message": "message",
    "sender" : "omer"
}


###
GET http://localhost:3000/post


###
GET http://localhost:3000/post/62e6844cbcbd99a4b96f197a